typography_spectrum: 0.729
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4375
  lightness: 0.7072802404873073
  saturation: 0.8125
  rhythmicContrast: 0.4007543285842985
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5526010126341134
analytics:
  google: null
  facebook: null
  twitter: null
name: Organo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Werk Slimmer & Niet Harder
purpose: []
